In [13]:
import pandas as pd

In [14]:
pd.set_option('display.max_columns', None)

In [15]:
df = pd.read_csv(r'C:\Users\mabin\Desktop\DataScienceClassNotes\Career247_Capstone_Project\Fraud_Detection_Project\data\raw\cleaned_data_v5.csv')

In [16]:
orginal_df = pd.read_csv(r'C:\Users\mabin\Desktop\DataScienceClassNotes\Career247_Capstone_Project\Fraud_Detection_Project\data\raw\transactions_fraud.csv')

In [17]:
df.head()

,transaction_date,payment_method,merchant_category,authentication_method,amount,ip_address_risk_score,device_trust_score,avg_amount_last_24h,device_change_flag,location_change_flag,merchant_historical_fraud_rate,cust_txn_count,cust_fraud_count,cust_fraud_rate,cust_avg_amt,device_count,merchant_fraud_rate,combined_risk,month,day,is_fraud
0,2024-01-01,WALLET,Travel,NONE,556.63,0.041787,0.841375,3294.64,0,0,0.063596,11,0,0.0,9659.361818,11,0.073620,0.029911,1,1,0
1,2024-01-01,CARD,Electronics,OTP,10158.89,0.162148,0.119578,4163.76,1,0,0.057505,11,0,0.0,9659.361818,11,0.099448,0.094997,1,1,0
2,2024-01-10,UPI,Fashion,PIN,15754.57,0.774662,0.718447,5077.26,0,1,0.053729,11,0,0.0,9659.361818,11,0.077844,0.102428,1,10,0
3,2024-01-20,CARD,Utilities,PIN,6095.68,0.259900,0.069586,1187.30,0,0,0.004334,11,0,0.0,9659.361818,11,0.086486,0.032338,1,20,0
4,2024-01-23,CARD,Gaming,OTP,15324.24,0.376711,0.286630,10936.02,0,0,0.131218,11,0,0.0,9659.361818,11,0.096386,0.086691,1,23,0

In [18]:
df.insert(loc=1, column='customer_id', value=orginal_df['customer_id'])

In [19]:
df.head()

,transaction_date,customer_id,payment_method,merchant_category,authentication_method,amount,ip_address_risk_score,device_trust_score,avg_amount_last_24h,device_change_flag,location_change_flag,merchant_historical_fraud_rate,cust_txn_count,cust_fraud_count,cust_fraud_rate,cust_avg_amt,device_count,merchant_fraud_rate,combined_risk,month,day,is_fraud
0,2024-01-01,1357,WALLET,Travel,NONE,556.63,0.041787,0.841375,3294.64,0,0,0.063596,11,0,0.0,9659.361818,11,0.073620,0.029911,1,1,0
1,2024-01-01,4095,CARD,Electronics,OTP,10158.89,0.162148,0.119578,4163.76,1,0,0.057505,11,0,0.0,9659.361818,11,0.099448,0.094997,1,1,0
2,2024-01-10,3618,UPI,Fashion,PIN,15754.57,0.774662,0.718447,5077.26,0,1,0.053729,11,0,0.0,9659.361818,11,0.077844,0.102428,1,10,0
3,2024-01-20,2755,CARD,Utilities,PIN,6095.68,0.259900,0.069586,1187.30,0,0,0.004334,11,0,0.0,9659.361818,11,0.086486,0.032338,1,20,0
4,2024-01-23,2732,CARD,Gaming,OTP,15324.24,0.376711,0.286630,10936.02,0,0,0.131218,11,0,0.0,9659.361818,11,0.096386,0.086691,1,23,0

In [20]:
# import pickle

# with open(r'C:\Users\mabin\Desktop\DataScienceClassNotes\Career247_Capstone_Project\Fraud_Detection_Project\src\models\df.pkl', 'wb') as file:
#     pickle.dump(df, file)

In [21]:
df['transaction_date'] = pd.to_datetime(df['transaction_date'])
df['transaction_date'].dt.day.max()

np.int32(31)

In [22]:
df.loc[df['customer_id'] == 1555]

,transaction_date,customer_id,payment_method,merchant_category,authentication_method,amount,ip_address_risk_score,device_trust_score,avg_amount_last_24h,device_change_flag,location_change_flag,merchant_historical_fraud_rate,cust_txn_count,cust_fraud_count,cust_fraud_rate,cust_avg_amt,device_count,merchant_fraud_rate,combined_risk,month,day,is_fraud
7857,2024-01-15,1555,UPI,Fashion,OTP,8348.62,0.867733,0.845567,2844.61,0,0,0.008306,13,2,0.500000,9005.624615,13,0.078947,0.236397,1,15,0
11844,2024-02-23,1555,CARD,Utilities,3DS,639.80,0.944960,0.640754,8457.99,0,0,0.072355,15,1,0.000000,9068.631333,15,0.146667,0.054025,2,23,0
12628,2024-02-16,1555,UPI,Gaming,OTP,12674.04,0.903529,0.197620,10348.97,0,0,0.090982,16,2,0.000000,9414.406875,16,0.127389,0.141493,2,16,0
13110,2024-01-11,1555,NETBANKING,Electronics,OTP,10676.01,0.656927,0.471950,8172.47,0,0,0.008421,13,2,0.000000,12789.011538,13,0.126437,0.141297,1,11,0
15872,2024-01-24,1555,WALLET,Utilities,OTP,1614.42,0.413187,0.623029,6261.76,0,0,0.147295,8,0,0.000000,4843.565000,8,0.134503,0.114098,1,24,0
21177,2024-01-15,1555,CARD,Gaming,OTP,15418.40,0.102170,0.162442,2905.10,0,1,0.018455,11,1,0.000000,10965.880909,11,0.123596,0.095367,1,15,0
25454,2024-01-14,1555,UPI,Electronics,3DS,7328.49,0.887668,0.797805,1226.13,0,0,0.048670,14,1,0.000000,7815.700714,14,0.109091,0.084221,1,14,0
26499,2024-03-01,1555,UPI,Utilities,OTP,3837.42,0.889674,0.473434,1363.08,0,0,0.148674,9,1,0.166667,10282.486667,9,0.099448,0.139818,3,1,0
27712,2024-02-22,1555,UPI,Fashion,OTP,5683.50,0.240346,0.925441,12803.86,0,1,0.027657,8,1,0.000000,7751.540000,8,0.064516,0.082306,2,22,0
28756,2024-02-24,1555,CARD,Utilities,OTP,9075.09,0.781063,0.263203,3044.12,1,0,0.101095,17,3,0.142857,8883.848824,17,0.136612,0.131674,2,24,1
35667,2024-02-20,1555,UPI,Fashion,OTP,16624.84,0.986302,0.670830,632.21,0,0,0.135327,13,1,0.000000,9459.472308,13,0.118056,0.038672,2,20,1
36761,2024-03-16,1555,NETBANKING,Gaming,OTP,11456.22,0.169148,0.142710,4816.80,0,0,0.118711,9,1,0.166667,8255.488889,9,0.074713,0.102713,3,16,0
42353,2024-02-07,1555,UPI,Utilities,NONE,10968.52,0.971610,0.703837,8529.35,0,0,0.011819,17,0,0.000000,11042.134706,17,0.137931,0.108545,2,7,0
42880,2024-01-12,1555,UPI,Gaming,OTP,11789.35,0.096394,0.910276,5796.41,0,0,0.139164,20,3,0.500000,9735.261500,20,0.095238,0.226674,1,12,0
45801,2024-03-30,1555,UPI,Electronics,NONE,3159.01,0.232269,0.094401,9573.44,0,0,0.119140,11,0,0.000000,8923.989091,11,0.096386,0.075426,3,30,0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   transaction_date                50000 non-null  datetime64[ns]
 1   customer_id                     50000 non-null  int64
 2   payment_method                  50000 non-null  object
 3   merchant_category               50000 non-null  object
 4   authentication_method           50000 non-null  object
 5   amount                          50000 non-null  float64
 6   ip_address_risk_score           50000 non-null  float64
 7   device_trust_score              50000 non-null  float64
 8   avg_amount_last_24h             50000 non-null  float64
 9   device_change_flag              50000 non-null  int64
 10  location_change_flag            50000 non-null  int64
 11  merchant_historical_fraud_rate  50000 non-null  float64
 12  cust_txn_count                  50000 non-null  int64
 13  cust_fraud_count                50000 non-null  int64
 14  cust_fraud_rate                 50000 non-null  float64
 15  cust_avg_amt                    50000 non-null  float64
 16  device_count                    50000 non-null  int64
 17  merchant_fraud_rate             50000 non-null  float64
 18  combined_risk                   50000 non-null  float64
 19  month                           50000 non-null  int64
 20  day                             50000 non-null  int64
 21  is_fraud                        50000 non-null  int64
dtypes: datetime64[ns](1), float64(9), int64(9), object(3)
memory usage: 8.4+ MB

In [24]:
df[df['is_fraud'] == 1].head()

,transaction_date,customer_id,payment_method,merchant_category,authentication_method,amount,ip_address_risk_score,device_trust_score,avg_amount_last_24h,device_change_flag,location_change_flag,merchant_historical_fraud_rate,cust_txn_count,cust_fraud_count,cust_fraud_rate,cust_avg_amt,device_count,merchant_fraud_rate,combined_risk,month,day,is_fraud
19,2024-02-20,2801,CARD,Electronics,OTP,14152.56,0.605990,0.063483,11403.11,0,0,0.081010,13,1,0.000000,10754.293077,13,0.081340,0.103900,2,20,1
32,2024-02-28,1368,UPI,Gaming,OTP,1707.58,0.092831,0.712067,13983.48,0,1,0.149972,16,3,0.000000,9062.510000,16,0.093023,0.048922,2,28,1
34,2024-03-08,4551,UPI,Utilities,OTP,6826.20,0.471950,0.174313,13890.06,0,1,0.007541,16,3,0.100000,9062.510000,16,0.102410,0.168155,3,8,1
36,2024-03-13,4433,UPI,Gaming,OTP,4151.72,0.591397,0.981913,6743.15,0,0,0.100345,16,3,0.166667,9062.510000,16,0.129032,0.206841,3,13,1
42,2024-01-25,3802,UPI,Fashion,OTP,13278.76,0.740575,0.126326,5971.45,1,0,0.057305,8,1,0.000000,7977.057500,8,0.085227,0.144581,1,25,1